// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package inject

import (
	"go.uber.org/zap"
	"graphy/cmd/graphy/neo"
	"graphy/storage/graph"
	"graphy/transport/graphql"
	"graphy/transport/http"
)

// Injectors from wire.go:

func InitialiseAppServer(logger *zap.Logger) (*http.AppServer, func(), error) {
	authToken := neo.NewBasicAuth()
	driver, cleanup, err := neo.NewDriver(authToken, logger)
	if err != nil {
		return nil, nil, err
	}
	roundRepository := graph.NewRoundRepository(driver, logger)
	resolver := graphql.NewResolver(roundRepository, logger)
	appServer := http.New(resolver, logger)
	return appServer, func() {
		cleanup()
	}, nil
}
