// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UserError interface {
	IsUserError()
}

type DuplicateNameError struct {
	Message         string `json:"message"`
	DuplicatedRound *Round `json:"duplicatedRound"`
}

func (DuplicateNameError) IsUserError() {}

type InvalidSequenceNumberError struct {
	Message string `json:"message"`
}

func (InvalidSequenceNumberError) IsUserError() {}

type Round struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	SequenceNo      int    `json:"sequenceNo"`
	RoutingCode     string `json:"routingCode"`
	ProvisionalDate string `json:"provisionalDate"`
}

type RoundInput struct {
	Name            *string `json:"name"`
	SequenceNo      *int    `json:"sequenceNo"`
	RoutingCode     *string `json:"routingCode"`
	ProvisionalDate *string `json:"provisionalDate"`
}

type RoundUpdateResult struct {
	UserErrors []UserError `json:"userErrors"`
	Round      *Round      `json:"round"`
}
